pub mod binance_feed;
pub mod chainlink_feed;
pub mod clob_feed;
pub(crate) mod util;

/// Messages sent from feeds to the main loop.
#[derive(Debug)]
pub enum FeedMessage {
    BinanceTrade {
        price: f64,
        quantity: f64,
        signed_quantity: Option<f64>,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        source_topic: Option<String>,
        source_symbol: Option<String>,
        sequence_key: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    BinanceBookTicker {
        best_bid: f64,
        best_ask: f64,
        bid_size: f64,
        ask_size: f64,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        source_topic: Option<String>,
        source_symbol: Option<String>,
        sequence_key: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    BinanceDepth {
        bid_levels: Vec<crate::types::OrderLevel>,
        ask_levels: Vec<crate::types::OrderLevel>,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        source_topic: Option<String>,
        source_symbol: Option<String>,
        sequence_key: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    ChainlinkPrice {
        price: f64,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        source_topic: Option<String>,
        source_symbol: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    ClobBook {
        book_state: crate::types::BookState,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        asset_id: Option<String>,
        source_topic: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    ClobPriceChange {
        book_state: crate::types::BookState,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        asset_id: Option<String>,
        source_topic: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    ClobBestBidAsk {
        book_state: crate::types::BookState,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        asset_id: Option<String>,
        source_topic: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    ClobMetaEvent {
        event_type: String,
        timestamp_ms: u64,
        timestamp_us: Option<u64>,
        asset_id: Option<String>,
        source_topic: Option<String>,
        connection_id: String,
        payload_json: Option<String>,
        details_json: Option<String>,
    },
    FeedConnected {
        name: String,
        connection_id: String,
    },
    FeedDisconnected {
        name: String,
        connection_id: Option<String>,
    },
    ChainlinkStale {
        connection_id: Option<String>,
    },
}
