export const empty = {
  noOpenTrades: "No open trades.",
  noSettledTrades: "No settled trades yet.",
  noActiveAlerts: "No active alerts.",
  noPolymarketSnapshot: "No Polymarket account snapshot yet.",
  noActiveMarket: "No active market window.",
  noVenueOrders: "No venue orders recorded.",
  noVenueFills: "No venue fills recorded.",
  noRedemptions: "No redemptions recorded.",
  noReconciliation: "No reconciliation events recorded.",
  noLogsMatch: "No log lines match the current filters.",
  noMarketLinked: "No market linked",
};

export const help = {
  hwm: "Highest balance observed since the run started.",
  winRate: "Percentage of settled trades that closed in profit.",
  wlRatio: "Settled wins over settled losses.",
  maxDrawdown: "Largest peak-to-trough drop since the run started.",
  uptime: "Total time the bot has been running in this process.",
  shadow: "Simulated trade recorded by the bot without touching Polymarket.",
  baseline: "Starting balance row that anchors the equity curve.",
  readonly: "Live data is observed but no orders are placed.",
  unavailable: "Action not available right now; reason shown below.",
  preflight: "Pre-trade safety checks.",
  arm: "Enable live order placement.",
  disarm: "Disable live order placement.",
  stopAfterFlat: "Stop running once open exposure is closed.",
  killSwitch: "Immediate stop, cancel orders, do not retry.",
  cashAvailable: "Settled USDC available for new orders.",
  reserved: "Cash currently locked behind open orders.",
  inventoryMark: "Current value of open positions at last mark.",
  redeemable: "Value of resolved positions waiting to be redeemed.",
  pendingRedeem: "Redemptions submitted but not yet credited.",
  allowance: "ERC-20 spending allowance granted to the venue.",
  proxy: "Polymarket gnosis proxy wallet address.",
  reconciliation: "Comparison between local state and venue-reported state.",
  criticalDivergence: "Local and remote state disagree by a material amount.",
  sessionFingerprint: "Hash of the config that started this live session.",
  cashCap: "Maximum total cash the bot is allowed to use.",
  burst: "Cluster of signals with no gap longer than the quiet gap.",
  quietGap: "Duration that splits one burst from the next.",
  momentum: "Short-term price change the strategy used to decide direction.",
  rollups: "Periodic summary log lines produced by the bot.",
  feedEvents: "Connection and subscription changes for upstream feeds.",
};
